package com.sc.zhenli.common.model;

import java.math.BigDecimal;
import java.util.Date;

public class RelOrderProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_order_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_order_product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_order_product.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_order_product.raw_price
     *
     * @mbggenerated
     */
    private BigDecimal rawPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_order_product.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_order_product.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_order_product.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_order_product.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_order_product.rel_order_id
     *
     * @mbggenerated
     */
    private Integer relOrderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_order_product.id
     *
     * @return the value of rel_order_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_order_product.id
     *
     * @param id the value for rel_order_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_order_product.product_id
     *
     * @return the value of rel_order_product.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_order_product.product_id
     *
     * @param productId the value for rel_order_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_order_product.product_name
     *
     * @return the value of rel_order_product.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_order_product.product_name
     *
     * @param productName the value for rel_order_product.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_order_product.raw_price
     *
     * @return the value of rel_order_product.raw_price
     *
     * @mbggenerated
     */
    public BigDecimal getRawPrice() {
        return rawPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_order_product.raw_price
     *
     * @param rawPrice the value for rel_order_product.raw_price
     *
     * @mbggenerated
     */
    public void setRawPrice(BigDecimal rawPrice) {
        this.rawPrice = rawPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_order_product.num
     *
     * @return the value of rel_order_product.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_order_product.num
     *
     * @param num the value for rel_order_product.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_order_product.discount
     *
     * @return the value of rel_order_product.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_order_product.discount
     *
     * @param discount the value for rel_order_product.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_order_product.create_date
     *
     * @return the value of rel_order_product.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_order_product.create_date
     *
     * @param createDate the value for rel_order_product.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_order_product.creater
     *
     * @return the value of rel_order_product.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_order_product.creater
     *
     * @param creater the value for rel_order_product.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_order_product.rel_order_id
     *
     * @return the value of rel_order_product.rel_order_id
     *
     * @mbggenerated
     */
    public Integer getRelOrderId() {
        return relOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_order_product.rel_order_id
     *
     * @param relOrderId the value for rel_order_product.rel_order_id
     *
     * @mbggenerated
     */
    public void setRelOrderId(Integer relOrderId) {
        this.relOrderId = relOrderId;
    }
}