package com.sc.zhenli.common.dao;

import com.sc.zhenli.common.model.RelOrderProduct;
import com.sc.zhenli.common.model.RelOrderProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelOrderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    int countByExample(RelOrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    int deleteByExample(RelOrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    int insert(RelOrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    int insertSelective(RelOrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    List<RelOrderProduct> selectByExample(RelOrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    RelOrderProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RelOrderProduct record, @Param("example") RelOrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RelOrderProduct record, @Param("example") RelOrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelOrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelOrderProduct record);
}